2025-10-24 22:33:07,210 ERROR: Unhandled Exception: [in C:\Users\zbapu\OneDrive\Desktop\ServiceHub\app.py:354]
Traceback (most recent call last):
  File "C:\Users\zbapu\AppData\Roaming\Python\Python313\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\zbapu\AppData\Roaming\Python\Python313\site-packages\flask\app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\zbapu\AppData\Roaming\Python\Python313\site-packages\flask\app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zbapu\AppData\Roaming\Python\Python313\site-packages\flask\ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\zbapu\AppData\Roaming\Python\Python313\site-packages\werkzeug\routing\map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\zbapu\AppData\Roaming\Python\Python313\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\zbapu\AppData\Roaming\Python\Python313\site-packages\flask\app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\zbapu\AppData\Roaming\Python\Python313\site-packages\flask\app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zbapu\AppData\Roaming\Python\Python313\site-packages\flask\ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\zbapu\AppData\Roaming\Python\Python313\site-packages\werkzeug\routing\map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-10-24 22:33:40,606 ERROR: Unhandled Exception: [in C:\Users\zbapu\OneDrive\Desktop\ServiceHub\app.py:354]
Traceback (most recent call last):
  File "C:\Users\zbapu\AppData\Roaming\Python\Python313\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\zbapu\AppData\Roaming\Python\Python313\site-packages\flask\app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\zbapu\AppData\Roaming\Python\Python313\site-packages\flask\app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zbapu\AppData\Roaming\Python\Python313\site-packages\flask\ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\zbapu\AppData\Roaming\Python\Python313\site-packages\werkzeug\routing\map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\zbapu\AppData\Roaming\Python\Python313\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\zbapu\AppData\Roaming\Python\Python313\site-packages\flask\app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\zbapu\AppData\Roaming\Python\Python313\site-packages\flask\app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zbapu\AppData\Roaming\Python\Python313\site-packages\flask\ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\zbapu\AppData\Roaming\Python\Python313\site-packages\werkzeug\routing\map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-10-24 22:45:03,171 ERROR: Unhandled Exception: [in C:\Users\zbapu\OneDrive\Desktop\ServiceHub\app.py:396]
Traceback (most recent call last):
  File "C:\Users\zbapu\AppData\Roaming\Python\Python313\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\zbapu\AppData\Roaming\Python\Python313\site-packages\flask\app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\zbapu\AppData\Roaming\Python\Python313\site-packages\flask\app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zbapu\AppData\Roaming\Python\Python313\site-packages\flask\ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\zbapu\AppData\Roaming\Python\Python313\site-packages\werkzeug\routing\map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\zbapu\AppData\Roaming\Python\Python313\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\zbapu\AppData\Roaming\Python\Python313\site-packages\flask\app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\zbapu\AppData\Roaming\Python\Python313\site-packages\flask\app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zbapu\AppData\Roaming\Python\Python313\site-packages\flask\ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\zbapu\AppData\Roaming\Python\Python313\site-packages\werkzeug\routing\map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
